// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PicCollectionModelPB.proto

package com.leeco.protobuf;

public final class Le_PicCollectionModelPB {
  private Le_PicCollectionModelPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PicCollectionModelPBOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .LTHeaderModelPB header = 1;
    boolean hasHeader();
    com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB getHeader();
    com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder getHeaderOrBuilder();
    
    // optional string pic1024_387 = 2;
    boolean hasPic1024387();
    String getPic1024387();
    
    // optional string pic800_407 = 3;
    boolean hasPic800407();
    String getPic800407();
    
    // optional string pic214_161 = 4;
    boolean hasPic214161();
    String getPic214161();
    
    // optional string pic120_90 = 5;
    boolean hasPic12090();
    String getPic12090();
    
    // optional string pic150_200 = 6;
    boolean hasPic150200();
    String getPic150200();
    
    // optional string pic200_150 = 7;
    boolean hasPic200150();
    String getPic200150();
    
    // optional string pic400_300 = 8;
    boolean hasPic400300();
    String getPic400300();
    
    // optional string pic300_400 = 9;
    boolean hasPic300400();
    String getPic300400();
    
    // optional string pic320_200 = 10;
    boolean hasPic320200();
    String getPic320200();
    
    // optional string pic300_300 = 11;
    boolean hasPic300300();
    String getPic300300();
    
    // optional string pic169 = 12;
    boolean hasPic169();
    String getPic169();
  }
  public static final class PicCollectionModelPB extends
      com.google.protobuf.GeneratedMessage
      implements PicCollectionModelPBOrBuilder {
    // Use PicCollectionModelPB.newBuilder() to construct.
    private PicCollectionModelPB(Builder builder) {
      super(builder);
    }
    private PicCollectionModelPB(boolean noInit) {}
    
    private static final PicCollectionModelPB defaultInstance;
    public static PicCollectionModelPB getDefaultInstance() {
      return defaultInstance;
    }
    
    public PicCollectionModelPB getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leeco.protobuf.Le_PicCollectionModelPB.internal_static_PicCollectionModelPB_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leeco.protobuf.Le_PicCollectionModelPB.internal_static_PicCollectionModelPB_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .LTHeaderModelPB header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB header_;
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB getHeader() {
      return header_;
    }
    public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder getHeaderOrBuilder() {
      return header_;
    }
    
    // optional string pic1024_387 = 2;
    public static final int PIC1024_387_FIELD_NUMBER = 2;
    private java.lang.Object pic1024387_;
    public boolean hasPic1024387() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPic1024387() {
      java.lang.Object ref = pic1024387_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pic1024387_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPic1024387Bytes() {
      java.lang.Object ref = pic1024387_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pic1024387_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pic800_407 = 3;
    public static final int PIC800_407_FIELD_NUMBER = 3;
    private java.lang.Object pic800407_;
    public boolean hasPic800407() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPic800407() {
      java.lang.Object ref = pic800407_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pic800407_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPic800407Bytes() {
      java.lang.Object ref = pic800407_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pic800407_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pic214_161 = 4;
    public static final int PIC214_161_FIELD_NUMBER = 4;
    private java.lang.Object pic214161_;
    public boolean hasPic214161() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getPic214161() {
      java.lang.Object ref = pic214161_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pic214161_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPic214161Bytes() {
      java.lang.Object ref = pic214161_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pic214161_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pic120_90 = 5;
    public static final int PIC120_90_FIELD_NUMBER = 5;
    private java.lang.Object pic12090_;
    public boolean hasPic12090() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getPic12090() {
      java.lang.Object ref = pic12090_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pic12090_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPic12090Bytes() {
      java.lang.Object ref = pic12090_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pic12090_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pic150_200 = 6;
    public static final int PIC150_200_FIELD_NUMBER = 6;
    private java.lang.Object pic150200_;
    public boolean hasPic150200() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getPic150200() {
      java.lang.Object ref = pic150200_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pic150200_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPic150200Bytes() {
      java.lang.Object ref = pic150200_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pic150200_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pic200_150 = 7;
    public static final int PIC200_150_FIELD_NUMBER = 7;
    private java.lang.Object pic200150_;
    public boolean hasPic200150() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getPic200150() {
      java.lang.Object ref = pic200150_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pic200150_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPic200150Bytes() {
      java.lang.Object ref = pic200150_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pic200150_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pic400_300 = 8;
    public static final int PIC400_300_FIELD_NUMBER = 8;
    private java.lang.Object pic400300_;
    public boolean hasPic400300() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getPic400300() {
      java.lang.Object ref = pic400300_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pic400300_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPic400300Bytes() {
      java.lang.Object ref = pic400300_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pic400300_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pic300_400 = 9;
    public static final int PIC300_400_FIELD_NUMBER = 9;
    private java.lang.Object pic300400_;
    public boolean hasPic300400() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getPic300400() {
      java.lang.Object ref = pic300400_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pic300400_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPic300400Bytes() {
      java.lang.Object ref = pic300400_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pic300400_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pic320_200 = 10;
    public static final int PIC320_200_FIELD_NUMBER = 10;
    private java.lang.Object pic320200_;
    public boolean hasPic320200() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getPic320200() {
      java.lang.Object ref = pic320200_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pic320200_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPic320200Bytes() {
      java.lang.Object ref = pic320200_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pic320200_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pic300_300 = 11;
    public static final int PIC300_300_FIELD_NUMBER = 11;
    private java.lang.Object pic300300_;
    public boolean hasPic300300() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public String getPic300300() {
      java.lang.Object ref = pic300300_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pic300300_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPic300300Bytes() {
      java.lang.Object ref = pic300300_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pic300300_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pic169 = 12;
    public static final int PIC169_FIELD_NUMBER = 12;
    private java.lang.Object pic169_;
    public boolean hasPic169() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getPic169() {
      java.lang.Object ref = pic169_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pic169_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPic169Bytes() {
      java.lang.Object ref = pic169_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pic169_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      header_ = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDefaultInstance();
      pic1024387_ = "";
      pic800407_ = "";
      pic214161_ = "";
      pic12090_ = "";
      pic150200_ = "";
      pic200150_ = "";
      pic400300_ = "";
      pic300400_ = "";
      pic320200_ = "";
      pic300300_ = "";
      pic169_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPic1024387Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPic800407Bytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPic214161Bytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPic12090Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getPic150200Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getPic200150Bytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getPic400300Bytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getPic300400Bytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getPic320200Bytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getPic300300Bytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getPic169Bytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPic1024387Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPic800407Bytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPic214161Bytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPic12090Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPic150200Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getPic200150Bytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getPic400300Bytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getPic300400Bytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getPic320200Bytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getPic300300Bytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getPic169Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leeco.protobuf.Le_PicCollectionModelPB.internal_static_PicCollectionModelPB_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leeco.protobuf.Le_PicCollectionModelPB.internal_static_PicCollectionModelPB_fieldAccessorTable;
      }
      
      // Construct using com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        pic1024387_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        pic800407_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        pic214161_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        pic12090_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        pic150200_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        pic200150_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        pic400300_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        pic300400_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        pic320200_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        pic300300_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        pic169_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB.getDescriptor();
      }
      
      public com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB getDefaultInstanceForType() {
        return com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB.getDefaultInstance();
      }
      
      public com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB build() {
        com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB buildPartial() {
        com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB result = new com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pic1024387_ = pic1024387_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pic800407_ = pic800407_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pic214161_ = pic214161_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.pic12090_ = pic12090_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.pic150200_ = pic150200_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.pic200150_ = pic200150_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.pic400300_ = pic400300_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.pic300400_ = pic300400_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.pic320200_ = pic320200_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.pic300300_ = pic300300_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.pic169_ = pic169_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB) {
          return mergeFrom((com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB other) {
        if (other == com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasPic1024387()) {
          setPic1024387(other.getPic1024387());
        }
        if (other.hasPic800407()) {
          setPic800407(other.getPic800407());
        }
        if (other.hasPic214161()) {
          setPic214161(other.getPic214161());
        }
        if (other.hasPic12090()) {
          setPic12090(other.getPic12090());
        }
        if (other.hasPic150200()) {
          setPic150200(other.getPic150200());
        }
        if (other.hasPic200150()) {
          setPic200150(other.getPic200150());
        }
        if (other.hasPic400300()) {
          setPic400300(other.getPic400300());
        }
        if (other.hasPic300400()) {
          setPic300400(other.getPic300400());
        }
        if (other.hasPic320200()) {
          setPic320200(other.getPic320200());
        }
        if (other.hasPic300300()) {
          setPic300300(other.getPic300300());
        }
        if (other.hasPic169()) {
          setPic169(other.getPic169());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder subBuilder = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.newBuilder();
              if (hasHeader()) {
                subBuilder.mergeFrom(getHeader());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHeader(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              pic1024387_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              pic800407_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              pic214161_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              pic12090_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              pic150200_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              pic200150_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              pic400300_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              pic300400_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              pic320200_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              pic300300_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              pic169_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .LTHeaderModelPB header = 1;
      private com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB header_ = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder> headerBuilder_;
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      public Builder setHeader(com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setHeader(
          com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeHeader(com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDefaultInstance()) {
            header_ =
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }
      
      // optional string pic1024_387 = 2;
      private java.lang.Object pic1024387_ = "";
      public boolean hasPic1024387() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPic1024387() {
        java.lang.Object ref = pic1024387_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pic1024387_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPic1024387(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pic1024387_ = value;
        onChanged();
        return this;
      }
      public Builder clearPic1024387() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pic1024387_ = getDefaultInstance().getPic1024387();
        onChanged();
        return this;
      }
      void setPic1024387(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        pic1024387_ = value;
        onChanged();
      }
      
      // optional string pic800_407 = 3;
      private java.lang.Object pic800407_ = "";
      public boolean hasPic800407() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPic800407() {
        java.lang.Object ref = pic800407_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pic800407_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPic800407(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pic800407_ = value;
        onChanged();
        return this;
      }
      public Builder clearPic800407() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pic800407_ = getDefaultInstance().getPic800407();
        onChanged();
        return this;
      }
      void setPic800407(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        pic800407_ = value;
        onChanged();
      }
      
      // optional string pic214_161 = 4;
      private java.lang.Object pic214161_ = "";
      public boolean hasPic214161() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getPic214161() {
        java.lang.Object ref = pic214161_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pic214161_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPic214161(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        pic214161_ = value;
        onChanged();
        return this;
      }
      public Builder clearPic214161() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pic214161_ = getDefaultInstance().getPic214161();
        onChanged();
        return this;
      }
      void setPic214161(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        pic214161_ = value;
        onChanged();
      }
      
      // optional string pic120_90 = 5;
      private java.lang.Object pic12090_ = "";
      public boolean hasPic12090() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getPic12090() {
        java.lang.Object ref = pic12090_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pic12090_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPic12090(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        pic12090_ = value;
        onChanged();
        return this;
      }
      public Builder clearPic12090() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pic12090_ = getDefaultInstance().getPic12090();
        onChanged();
        return this;
      }
      void setPic12090(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        pic12090_ = value;
        onChanged();
      }
      
      // optional string pic150_200 = 6;
      private java.lang.Object pic150200_ = "";
      public boolean hasPic150200() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getPic150200() {
        java.lang.Object ref = pic150200_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pic150200_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPic150200(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        pic150200_ = value;
        onChanged();
        return this;
      }
      public Builder clearPic150200() {
        bitField0_ = (bitField0_ & ~0x00000020);
        pic150200_ = getDefaultInstance().getPic150200();
        onChanged();
        return this;
      }
      void setPic150200(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        pic150200_ = value;
        onChanged();
      }
      
      // optional string pic200_150 = 7;
      private java.lang.Object pic200150_ = "";
      public boolean hasPic200150() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getPic200150() {
        java.lang.Object ref = pic200150_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pic200150_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPic200150(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        pic200150_ = value;
        onChanged();
        return this;
      }
      public Builder clearPic200150() {
        bitField0_ = (bitField0_ & ~0x00000040);
        pic200150_ = getDefaultInstance().getPic200150();
        onChanged();
        return this;
      }
      void setPic200150(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        pic200150_ = value;
        onChanged();
      }
      
      // optional string pic400_300 = 8;
      private java.lang.Object pic400300_ = "";
      public boolean hasPic400300() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getPic400300() {
        java.lang.Object ref = pic400300_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pic400300_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPic400300(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        pic400300_ = value;
        onChanged();
        return this;
      }
      public Builder clearPic400300() {
        bitField0_ = (bitField0_ & ~0x00000080);
        pic400300_ = getDefaultInstance().getPic400300();
        onChanged();
        return this;
      }
      void setPic400300(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        pic400300_ = value;
        onChanged();
      }
      
      // optional string pic300_400 = 9;
      private java.lang.Object pic300400_ = "";
      public boolean hasPic300400() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getPic300400() {
        java.lang.Object ref = pic300400_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pic300400_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPic300400(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        pic300400_ = value;
        onChanged();
        return this;
      }
      public Builder clearPic300400() {
        bitField0_ = (bitField0_ & ~0x00000100);
        pic300400_ = getDefaultInstance().getPic300400();
        onChanged();
        return this;
      }
      void setPic300400(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        pic300400_ = value;
        onChanged();
      }
      
      // optional string pic320_200 = 10;
      private java.lang.Object pic320200_ = "";
      public boolean hasPic320200() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getPic320200() {
        java.lang.Object ref = pic320200_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pic320200_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPic320200(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        pic320200_ = value;
        onChanged();
        return this;
      }
      public Builder clearPic320200() {
        bitField0_ = (bitField0_ & ~0x00000200);
        pic320200_ = getDefaultInstance().getPic320200();
        onChanged();
        return this;
      }
      void setPic320200(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        pic320200_ = value;
        onChanged();
      }
      
      // optional string pic300_300 = 11;
      private java.lang.Object pic300300_ = "";
      public boolean hasPic300300() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getPic300300() {
        java.lang.Object ref = pic300300_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pic300300_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPic300300(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        pic300300_ = value;
        onChanged();
        return this;
      }
      public Builder clearPic300300() {
        bitField0_ = (bitField0_ & ~0x00000400);
        pic300300_ = getDefaultInstance().getPic300300();
        onChanged();
        return this;
      }
      void setPic300300(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        pic300300_ = value;
        onChanged();
      }
      
      // optional string pic169 = 12;
      private java.lang.Object pic169_ = "";
      public boolean hasPic169() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getPic169() {
        java.lang.Object ref = pic169_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pic169_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPic169(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        pic169_ = value;
        onChanged();
        return this;
      }
      public Builder clearPic169() {
        bitField0_ = (bitField0_ & ~0x00000800);
        pic169_ = getDefaultInstance().getPic169();
        onChanged();
        return this;
      }
      void setPic169(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        pic169_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:PicCollectionModelPB)
    }
    
    static {
      defaultInstance = new PicCollectionModelPB(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PicCollectionModelPB)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PicCollectionModelPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PicCollectionModelPB_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032PicCollectionModelPB.proto\032\025LTHeaderMo" +
      "delPB.proto\"\220\002\n\024PicCollectionModelPB\022 \n\006" +
      "header\030\001 \001(\0132\020.LTHeaderModelPB\022\023\n\013pic102" +
      "4_387\030\002 \001(\t\022\022\n\npic800_407\030\003 \001(\t\022\022\n\npic21" +
      "4_161\030\004 \001(\t\022\021\n\tpic120_90\030\005 \001(\t\022\022\n\npic150" +
      "_200\030\006 \001(\t\022\022\n\npic200_150\030\007 \001(\t\022\022\n\npic400" +
      "_300\030\010 \001(\t\022\022\n\npic300_400\030\t \001(\t\022\022\n\npic320" +
      "_200\030\n \001(\t\022\022\n\npic300_300\030\013 \001(\t\022\016\n\006pic169" +
      "\030\014 \001(\tB-\n\022com.leeco.protobufB\027Le_PicColl" +
      "ectionModelPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PicCollectionModelPB_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PicCollectionModelPB_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PicCollectionModelPB_descriptor,
              new java.lang.String[] { "Header", "Pic1024387", "Pic800407", "Pic214161", "Pic12090", "Pic150200", "Pic200150", "Pic400300", "Pic300400", "Pic320200", "Pic300300", "Pic169", },
              com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB.class,
              com.leeco.protobuf.Le_PicCollectionModelPB.PicCollectionModelPB.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.leeco.protobuf.Le_LTHeaderModelPB.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
