// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LTHeaderModelPB.proto

package com.leeco.protobuf;

public final class Le_LTHeaderModelPB {
  private Le_LTHeaderModelPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LTHeaderModelPBOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 status = 1;
    boolean hasStatus();
    int getStatus();
    
    // optional string markid = 2;
    boolean hasMarkid();
    String getMarkid();
    
    // optional .LTHeaderErrorPB error = 3;
    boolean hasError();
    com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB getError();
    com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPBOrBuilder getErrorOrBuilder();
  }
  public static final class LTHeaderModelPB extends
      com.google.protobuf.GeneratedMessage
      implements LTHeaderModelPBOrBuilder {
    // Use LTHeaderModelPB.newBuilder() to construct.
    private LTHeaderModelPB(Builder builder) {
      super(builder);
    }
    private LTHeaderModelPB(boolean noInit) {}
    
    private static final LTHeaderModelPB defaultInstance;
    public static LTHeaderModelPB getDefaultInstance() {
      return defaultInstance;
    }
    
    public LTHeaderModelPB getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_LTHeaderModelPB_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_LTHeaderModelPB_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getStatus() {
      return status_;
    }
    
    // optional string markid = 2;
    public static final int MARKID_FIELD_NUMBER = 2;
    private java.lang.Object markid_;
    public boolean hasMarkid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMarkid() {
      java.lang.Object ref = markid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          markid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMarkidBytes() {
      java.lang.Object ref = markid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        markid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .LTHeaderErrorPB error = 3;
    public static final int ERROR_FIELD_NUMBER = 3;
    private com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB getError() {
      return error_;
    }
    public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPBOrBuilder getErrorOrBuilder() {
      return error_;
    }
    
    private void initFields() {
      status_ = 0;
      markid_ = "";
      error_ = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMarkidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, error_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMarkidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, error_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_LTHeaderModelPB_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_LTHeaderModelPB_fieldAccessorTable;
      }
      
      // Construct using com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getErrorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        markid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (errorBuilder_ == null) {
          error_ = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.getDefaultInstance();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDescriptor();
      }
      
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB getDefaultInstanceForType() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDefaultInstance();
      }
      
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB build() {
        com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB buildPartial() {
        com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB result = new com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.markid_ = markid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB) {
          return mergeFrom((com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB other) {
        if (other == com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasMarkid()) {
          setMarkid(other.getMarkid());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              markid_ = input.readBytes();
              break;
            }
            case 26: {
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.Builder subBuilder = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.newBuilder();
              if (hasError()) {
                subBuilder.mergeFrom(getError());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setError(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 status = 1;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }
      
      // optional string markid = 2;
      private java.lang.Object markid_ = "";
      public boolean hasMarkid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMarkid() {
        java.lang.Object ref = markid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          markid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMarkid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        markid_ = value;
        onChanged();
        return this;
      }
      public Builder clearMarkid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        markid_ = getDefaultInstance().getMarkid();
        onChanged();
        return this;
      }
      void setMarkid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        markid_ = value;
        onChanged();
      }
      
      // optional .LTHeaderErrorPB error = 3;
      private com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB error_ = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.Builder, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPBOrBuilder> errorBuilder_;
      public boolean hasError() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB getError() {
        if (errorBuilder_ == null) {
          return error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      public Builder setError(com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setError(
          com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeError(com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              error_ != com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.getDefaultInstance()) {
            error_ =
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.getDefaultInstance();
          onChanged();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.Builder getErrorBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPBOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.Builder, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPBOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.Builder, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPBOrBuilder>(
                  error_,
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:LTHeaderModelPB)
    }
    
    static {
      defaultInstance = new LTHeaderModelPB(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:LTHeaderModelPB)
  }
  
  public interface LTHeaderErrorPBOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string code = 1;
    boolean hasCode();
    String getCode();
    
    // optional string content = 2;
    boolean hasContent();
    String getContent();
    
    // optional string extendmsg = 3;
    boolean hasExtendmsg();
    String getExtendmsg();
  }
  public static final class LTHeaderErrorPB extends
      com.google.protobuf.GeneratedMessage
      implements LTHeaderErrorPBOrBuilder {
    // Use LTHeaderErrorPB.newBuilder() to construct.
    private LTHeaderErrorPB(Builder builder) {
      super(builder);
    }
    private LTHeaderErrorPB(boolean noInit) {}
    
    private static final LTHeaderErrorPB defaultInstance;
    public static LTHeaderErrorPB getDefaultInstance() {
      return defaultInstance;
    }
    
    public LTHeaderErrorPB getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_LTHeaderErrorPB_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_LTHeaderErrorPB_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private java.lang.Object code_;
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          code_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private java.lang.Object content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          content_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string extendmsg = 3;
    public static final int EXTENDMSG_FIELD_NUMBER = 3;
    private java.lang.Object extendmsg_;
    public boolean hasExtendmsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getExtendmsg() {
      java.lang.Object ref = extendmsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          extendmsg_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getExtendmsgBytes() {
      java.lang.Object ref = extendmsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        extendmsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      code_ = "";
      content_ = "";
      extendmsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getContentBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getExtendmsgBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getContentBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getExtendmsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_LTHeaderErrorPB_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_LTHeaderErrorPB_fieldAccessorTable;
      }
      
      // Construct using com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        extendmsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.getDescriptor();
      }
      
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB getDefaultInstanceForType() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.getDefaultInstance();
      }
      
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB build() {
        com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB buildPartial() {
        com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB result = new com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.extendmsg_ = extendmsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB) {
          return mergeFrom((com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB other) {
        if (other == com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasExtendmsg()) {
          setExtendmsg(other.getExtendmsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              code_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              extendmsg_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string code = 1;
      private java.lang.Object code_ = "";
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      void setCode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
      }
      
      // optional string content = 2;
      private java.lang.Object content_ = "";
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      void setContent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
      }
      
      // optional string extendmsg = 3;
      private java.lang.Object extendmsg_ = "";
      public boolean hasExtendmsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getExtendmsg() {
        java.lang.Object ref = extendmsg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          extendmsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setExtendmsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        extendmsg_ = value;
        onChanged();
        return this;
      }
      public Builder clearExtendmsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        extendmsg_ = getDefaultInstance().getExtendmsg();
        onChanged();
        return this;
      }
      void setExtendmsg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        extendmsg_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:LTHeaderErrorPB)
    }
    
    static {
      defaultInstance = new LTHeaderErrorPB(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:LTHeaderErrorPB)
  }
  
  public interface PBDictionaryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string strDict = 1;
    boolean hasStrDict();
    String getStrDict();
  }
  public static final class PBDictionary extends
      com.google.protobuf.GeneratedMessage
      implements PBDictionaryOrBuilder {
    // Use PBDictionary.newBuilder() to construct.
    private PBDictionary(Builder builder) {
      super(builder);
    }
    private PBDictionary(boolean noInit) {}
    
    private static final PBDictionary defaultInstance;
    public static PBDictionary getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBDictionary getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_PBDictionary_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_PBDictionary_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string strDict = 1;
    public static final int STRDICT_FIELD_NUMBER = 1;
    private java.lang.Object strDict_;
    public boolean hasStrDict() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getStrDict() {
      java.lang.Object ref = strDict_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          strDict_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStrDictBytes() {
      java.lang.Object ref = strDict_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        strDict_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      strDict_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStrDictBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStrDictBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_PBDictionary_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_PBDictionary_fieldAccessorTable;
      }
      
      // Construct using com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        strDict_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary.getDescriptor();
      }
      
      public com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary getDefaultInstanceForType() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary.getDefaultInstance();
      }
      
      public com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary build() {
        com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary buildPartial() {
        com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary result = new com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.strDict_ = strDict_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary) {
          return mergeFrom((com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary other) {
        if (other == com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary.getDefaultInstance()) return this;
        if (other.hasStrDict()) {
          setStrDict(other.getStrDict());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              strDict_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string strDict = 1;
      private java.lang.Object strDict_ = "";
      public boolean hasStrDict() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getStrDict() {
        java.lang.Object ref = strDict_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          strDict_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStrDict(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strDict_ = value;
        onChanged();
        return this;
      }
      public Builder clearStrDict() {
        bitField0_ = (bitField0_ & ~0x00000001);
        strDict_ = getDefaultInstance().getStrDict();
        onChanged();
        return this;
      }
      void setStrDict(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        strDict_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:PBDictionary)
    }
    
    static {
      defaultInstance = new PBDictionary(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PBDictionary)
  }
  
  public interface LTPBCommonModelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .LTHeaderModelPB header = 1;
    boolean hasHeader();
    com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB getHeader();
    com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder getHeaderOrBuilder();
    
    // optional bytes data = 2;
    boolean hasData();
    com.google.protobuf.ByteString getData();
  }
  public static final class LTPBCommonModel extends
      com.google.protobuf.GeneratedMessage
      implements LTPBCommonModelOrBuilder {
    // Use LTPBCommonModel.newBuilder() to construct.
    private LTPBCommonModel(Builder builder) {
      super(builder);
    }
    private LTPBCommonModel(boolean noInit) {}
    
    private static final LTPBCommonModel defaultInstance;
    public static LTPBCommonModel getDefaultInstance() {
      return defaultInstance;
    }
    
    public LTPBCommonModel getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_LTPBCommonModel_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_LTPBCommonModel_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .LTHeaderModelPB header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB header_;
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB getHeader() {
      return header_;
    }
    public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder getHeaderOrBuilder() {
      return header_;
    }
    
    // optional bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    private void initFields() {
      header_ = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDefaultInstance();
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_LTPBCommonModel_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.internal_static_LTPBCommonModel_fieldAccessorTable;
      }
      
      // Construct using com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel.getDescriptor();
      }
      
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel getDefaultInstanceForType() {
        return com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel.getDefaultInstance();
      }
      
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel build() {
        com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel buildPartial() {
        com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel result = new com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel) {
          return mergeFrom((com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel other) {
        if (other == com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder subBuilder = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.newBuilder();
              if (hasHeader()) {
                subBuilder.mergeFrom(getHeader());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHeader(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .LTHeaderModelPB header = 1;
      private com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB header_ = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder> headerBuilder_;
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      public Builder setHeader(com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setHeader(
          com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeHeader(com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDefaultInstance()) {
            header_ =
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      public com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder, com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPBOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }
      
      // optional bytes data = 2;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:LTPBCommonModel)
    }
    
    static {
      defaultInstance = new LTPBCommonModel(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:LTPBCommonModel)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LTHeaderModelPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LTHeaderModelPB_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LTHeaderErrorPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LTHeaderErrorPB_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PBDictionary_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBDictionary_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LTPBCommonModel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LTPBCommonModel_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025LTHeaderModelPB.proto\"R\n\017LTHeaderModel" +
      "PB\022\016\n\006status\030\001 \001(\005\022\016\n\006markid\030\002 \001(\t\022\037\n\005er" +
      "ror\030\003 \001(\0132\020.LTHeaderErrorPB\"C\n\017LTHeaderE" +
      "rrorPB\022\014\n\004code\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\022\021\n" +
      "\textendmsg\030\003 \001(\t\"\037\n\014PBDictionary\022\017\n\007strD" +
      "ict\030\001 \001(\t\"A\n\017LTPBCommonModel\022 \n\006header\030\001" +
      " \001(\0132\020.LTHeaderModelPB\022\014\n\004data\030\002 \001(\014B(\n\022" +
      "com.leeco.protobufB\022Le_LTHeaderModelPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_LTHeaderModelPB_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_LTHeaderModelPB_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LTHeaderModelPB_descriptor,
              new java.lang.String[] { "Status", "Markid", "Error", },
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.class,
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderModelPB.Builder.class);
          internal_static_LTHeaderErrorPB_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_LTHeaderErrorPB_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LTHeaderErrorPB_descriptor,
              new java.lang.String[] { "Code", "Content", "Extendmsg", },
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.class,
              com.leeco.protobuf.Le_LTHeaderModelPB.LTHeaderErrorPB.Builder.class);
          internal_static_PBDictionary_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_PBDictionary_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PBDictionary_descriptor,
              new java.lang.String[] { "StrDict", },
              com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary.class,
              com.leeco.protobuf.Le_LTHeaderModelPB.PBDictionary.Builder.class);
          internal_static_LTPBCommonModel_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_LTPBCommonModel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LTPBCommonModel_descriptor,
              new java.lang.String[] { "Header", "Data", },
              com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel.class,
              com.leeco.protobuf.Le_LTHeaderModelPB.LTPBCommonModel.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
